### ISSUE TITLE
Sendmail issue

### ISSUE THREAD

**Issue by Daniel-KM** [getgrav/grav-plugin-email#71]
I use the plugin subscribe and since the last update, i get (the plugin subscribe was not updated since a while, but this one was updated): 
```
Swift_TransportException
Unsupported sendmail command flags [/usr/sbin/sendmail]. Must be one of "-bs" or "-t" but can include additional flags.
```

**Comment by Daniel-KM** [comment]
This is related to a bad process upgrade. The param -bs was not added automatically to the config.

**Comment by Daniel-KM** [comment]
But there is another issue related (see #72) to the fact that swiftmailer is not up to  date.

**Comment by yannicgraeser** [comment]
Where do I have to add -bs in the plugin config?

**Comment by Daniel-KM** [comment]
In the config of the plugin via the admin panel : https://example.com/admin/plugins/email

**Comment by bradlis7** [comment]
You can configure user/config/plugins/email.yaml directly by setting

```
mailer:
  sendmail:
    bin: '/usr/sbin/sendmail -bs'
```

This seemed to fix it for me.

**Comment by tgdallas** [comment]
I have the same problem -even worse...
I tested me email submission form and:
ALL pages in the website (including admin) except the home page comes up with this error!

Server Error
Sorry, something went terribly wrong!
0 - Unsupported sendmail command flags "/usr/sbin/sendmail"; must be one of "-bs" or "-t" but can include additional flags.
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.

The log is as follows:

[2025-07-26 08:35:42] grav.DEBUG: >>>> Saved cached forms: -form-plugin {"en":{"/":"-"}} [] []
[2025-07-26 08:37:53] grav.DEBUG: <<<< Loaded cached forms: 1d331f7c8e260eb1e5b6e07f9cf470f3-form-plugin {"en":{"/excursion":"-","/registration":"-","/contact":"-"}} [] []
[2025-07-26 08:37:54] grav.CRITICAL: Unsupported sendmail command flags "/usr/sbin/sendmail"; must be one of "-bs" or "-t" but can include additional flags. - Trace: #0 /home/vhosts/seac2026.uth.gr/htdocs/user/plugins/email/vendor/symfony/mailer/Transport/SendmailTransportFactory.php(24): Symfony\Component\Mailer\Transport\SendmailTransport->__construct() #1 /home/vhosts/seac2026.uth.gr/htdocs/user/plugins/email/vendor/symfony/mailer/Transport.php(172): Symfony\Component\Mailer\Transport\SendmailTransportFactory->create() #2 /home/vhosts/seac2026.uth.gr/htdocs/user/plugins/email/vendor/symfony/mailer/Transport.php(161): Symfony\Component\Mailer\Transport->fromDsnObject() #3 /home/vhosts/seac2026.uth.gr/htdocs/user/plugins/email/vendor/symfony/mailer/Transport.php(113): Symfony\Component\Mailer\Transport->parseDsn() #4 /home/vhosts/seac2026.uth.gr/htdocs/user/plugins/email/vendor/symfony/mailer/Transport.php(74): Symfony\Component\Mailer\Transport->fromString() #5 /home/vhosts/seac2026.uth.gr/htdocs/user/plugins/email/classes/Email.php(449): Symfony\Component\Mailer\Transport::fromDsn() #6 /home/vhosts/seac2026.uth.gr/htdocs/user/plugins/email/classes/Email.php(323): Grav\Plugin\Email\Email::getTransport() #7 /home/vhosts/seac2026.uth.gr/htdocs/user/plugins/email/classes/Email.php(39): Grav\Plugin\Email\Email->initMailer() #8 /home/vhosts/seac2026.uth.gr/htdocs/user/plugins/email/email.php(48): Grav\Plugin\Email\Email->__construct() #9 /home/vhosts/seac2026.uth.gr/htdocs/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Grav\Plugin\EmailPlugin->onPluginsInitialized() #10 /home/vhosts/seac2026.uth.gr/htdocs/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() #11 /home/vhosts/seac2026.uth.gr/htdocs/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners() #12 /home/vhosts/seac2026.uth.gr/htdocs/system/src/Grav/Common/Grav.php(597): Symfony\Component\EventDispatcher\EventDispatcher->dispatch() #13 /home/vhosts/seac2026.uth.gr/htdocs/system/src/Grav/Common/Processors/PluginsProcessor.php(36): Grav\Common\Grav->fireEvent() #14 /home/vhosts/seac2026.uth.gr/htdocs/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PluginsProcessor->process() #15 /home/vhosts/seac2026.uth.gr/htdocs/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #16 /home/vhosts/seac2026.uth.gr/htdocs/system/src/Grav/Common/Processors/InitializeProcessor.php(130): Grav\Framework\RequestHandler\RequestHandler->handle() #17 /home/vhosts/seac2026.uth.gr/htdocs/system/src/Grav/Common/Debugger.php(550): Grav\Common\Processors\InitializeProcessor::Grav\Common\Processors\{closure}() #18 /home/vhosts/seac2026.uth.gr/htdocs/system/src/Grav/Common/Processors/InitializeProcessor.php(129): Grav\Common\Debugger->profile() #19 /home/vhosts/seac2026.uth.gr/htdocs/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\InitializeProcessor->process() #20 /home/vhosts/seac2026.uth.gr/htdocs/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #21 /home/vhosts/seac2026.uth.gr/htdocs/system/src/Grav/Framework/RequestHandler/Middlewares/MultipartRequestSupport.php(40): Grav\Framework\RequestHandler\RequestHandler->handle() #22 /home/vhosts/seac2026.uth.gr/htdocs/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Framework\RequestHandler\Middlewares\MultipartRequestSupport->process() #23 /home/vhosts/seac2026.uth.gr/htdocs/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #24 /home/vhosts/seac2026.uth.gr/htdocs/system/src/Grav/Common/Grav.php(312): Grav\Framework\RequestHandler\RequestHandler->handle() #25 /home/vhosts/seac2026.uth.gr/htdocs/index.php(47): Grav\Common\Grav->process() #26 {main} [] []

I edited the user/config/plugins/email.yaml but to no avail.

Any ideas?
